

# Sutra test workflow: idiomatic Rust approach
# Run tests with:
#   cargo comprehensive-test [category] [suite]

[alias]
comprehensive-test = "run --bin test_runner"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
walkdir = "2"